[assign]

[rendered-link]
trigger-files = ["posts/"]

[ping.relnotes-interest-group]
message = """\
Hi relnotes-interest-group, this PR adds a release blog post. Could you review
the blog post if you have time? Thanks <3
"""
